# -*- coding: utf-8 -*-
"""RAG Otomotif.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvoU1YTpvNU5E9TFm_076LLktBLbMs11
"""

#pip install streamlit PyPDF2 google-generativeai requests

import streamlit as st
import requests
import os
import tempfile
from PyPDF2 import PdfReader
import google.generativeai as genai

# ===============================
# CONFIGURASI HALAMAN
# ===============================
st.set_page_config(page_title="Chatbox Tanya Penjualan Otomotif Indonesia", page_icon="🚗")

st.title("🚗 Chatbox Tanya Penjualan Otomotif Indonesia")
st.write("Gunakan chat ini untuk menanyakan data penjualan mobil di Indonesia berdasarkan data GAIKINDO.")

if not google_api_key:
    st.info("Masukkan Google API Key Anda di the sidebar to start chatting.", icon="🗝️")
    st.stop()

# ===============================
# INPUT GOOGLE API KEY
# ===============================
api_key = st.text_input("Masukkan Google API Key Anda:", type="password")
if not api_key:
    st.warning("Silakan masukkan API key untuk melanjutkan.")
    st.stop()

# Konfigurasi API Google
genai.configure(api_key=api_key)

# ===============================
# FUNGSI DOWNLOAD DAN EKSTRAK PDF
# ===============================
@st.cache_data(show_spinner=True)
def load_pdf_texts_from_github():
    base_url = "https://raw.githubusercontent.com/susantoarnang21/otomotifstreamlit/main/"
    pdf_files = [f"file{i}.pdf" for i in range(1, 10)]

    all_text = ""
    for pdf_file in pdf_files:
        url = base_url + pdf_file
        try:
            response = requests.get(url)
            if response.status_code == 200:
                with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
                    tmp.write(response.content)
                    tmp_path = tmp.name
                reader = PdfReader(tmp_path)
                text = ""
                for page in reader.pages:
                    text += page.extract_text() or ""
                all_text += f"\n=== {pdf_file} ===\n{text}\n"
                os.remove(tmp_path)
            else:
                st.warning(f"Gagal mengunduh {pdf_file}")
        except Exception as e:
            st.error(f"Error membaca {pdf_file}: {e}")
    return all_text

st.info("📄 Mengambil dan memproses data PDF dari GitHub...")
pdf_text = load_pdf_texts_from_github()

# ===============================
# CHAT INTERFACE
# ===============================
if "messages" not in st.session_state:
    st.session_state["messages"] = []

# Tampilkan riwayat chat
for msg in st.session_state["messages"]:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# Input dari pengguna
user_input = st.chat_input("Tanyakan sesuatu tentang penjualan otomotif...")

if user_input:
    # Simpan pesan pengguna
    st.session_state["messages"].append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)

    # Buat prompt kontekstual
    prompt = (
        "Anda adalah asisten data penjualan otomotif Indonesia.\n"
        "Gunakan konteks dari data GAIKINDO berikut untuk menjawab pertanyaan pengguna.\n\n"
        "=== DATA PENJUALAN OTOMOTIF GAIKINDO ===\n"
        f"{pdf_text[:15000]}\n"  # ambil sebagian teks agar tidak overload
        "=== AKHIR DATA ===\n\n"
        f"Pertanyaan: {user_input}\n"
        "Jawaban (berdasarkan data dan jelas):"
    )

    # Proses jawaban
    with st.chat_message("assistant"):
        with st.spinner("🔍 Menganalisis data..."):
            try:
                model = genai.GenerativeModel("gemini-1.5-pro")
                response = model.generate_content(prompt)
                answer = response.text
            except Exception as e:
                answer = f"Terjadi kesalahan saat memproses: {e}"

            st.markdown(answer)
            st.session_state["messages"].append({"role": "assistant", "content": answer})